### ISSUE TITLE
main.js error

### ISSUE THREAD

**Issue by ctt0124** [TonyJiangWJ/JingDongBeans#1]
14:41:52.428/E: TypeError: Cannot find function getSource in object com.stardust.autojs.engine.LoopBasedJavaScriptEngine@5ba53d2. (file:/storage/emulated/0/脚本/JingDongBeans/config.js#3)
 at script(file:/storage/emulated/0/脚本/JingDongBeans/config.js:3)
 at script(<init>:105)
 at script(<main>:8)

**Comment by TonyJiangWJ** [comment]
什么版本的AutoJS

**Comment by ctt0124** [comment]
> 什么版本的AutoJS

4.1.1 Alpha2

**Comment by TonyJiangWJ** [comment]
不至于吧 你确定没装错？

**Comment by ctt0124** [comment]
=.=肯定没错啊，我之前写了点评签到和收淘金币的，都用的好好的

**Comment by ctt0124** [comment]
咦~~~我今天再start居然可以了。
跟前几天系统OTA了有关吗

**Comment by TonyJiangWJ** [comment]
那不知道了 系统层面 每个手机都不一样
