### ISSUE TITLE
代码很好玩，能打开微信小游戏吗

### ISSUE THREAD

**Issue by fakers777** [TonyJiangWJ/JingDongBeans#2]
微信小游戏，有些也要领奖励，请问能自动化吗

**Comment by fakers777** [comment]
代码写的架构挺完善的，要是能发挥更大作用就好了

**Comment by TonyJiangWJ** [comment]
有兴趣可以查看这个项目[AutoScriptBase](https://github.com/TonyJiangWJ/AutoScriptBase)，可以基于它进行开发你想要的，基本骨架都搭好了。
京豆的基本没在维护了，更主要的还是在开发和维护[蚂蚁森林](https://github.com/TonyJiangWJ/Ant-Forest)和[蚂蚁庄园](https://github.com/TonyJiangWJ/Ant-Manor)。
